### ISSUE TITLE
ManagerBehaviour removes other ManagerTypes

### ISSUE THREAD

**Issue by CaptainRedmuff** [Evorlor/Temp-Custom-Unity-Library#1]
I am not sure if this is intended, but when creating different managers by subclassing the `ManagerBehaviour`, any other objects inheriting from `ManagerBehaviour` are removed from the scene graph.

I was under the impression that it would be possible to have multiple managers in a scene, such as 

- CameraManager
- AudioManager
- InputManger 

Where each of the above would inherit from `ManagerBehaviour`, as can be seen in your `AudioManager` class: https://github.com/Evorlor/Custom-Unity-Library/blob/master/Assets/Generic/Components/AudioManager.cs

When I create the above classes and add them to my scene, all but one of the managers is removed. I am guessing that this is because the `ManagerName` property is used to find other game objects here: https://github.com/Evorlor/Custom-Unity-Library/blob/master/Assets/Generic/Components/ManagerBehaviour.cs#L24

Am I using this class correctly, or should there only ever be *one* single instance of any manager component in a scene? I realise this is supposed to be a singleton pattern but I was under the impression that it would be possible to have multiple singletons in a scene.

**Comment by SamuelKnox** [comment]
You can have only one instance of each extended classes, but as many extensions of this class as you'd like. If you have 2 AudioManagers, one will be removed automatically. If you have an AudioManager and an InputManager, they should both be able to live. The Manager GameObject is only a default GameObject if the manager component has not yet been created. I am not clear as to what steps you are taking to fill create this bug, but I will look into it later today. Any other details you can find would be appreciated.

**Comment by CaptainRedmuff** [comment]
I have made 2 classes; an AudioManager and a CameraManager, both of which extend from `ManagerBehaviour`.

When I add a GameObject to the scene and add the applicable component, the object is removed entirely only leaving one of the two.

Steps to recreate:

Create an AudioManager class which extends from `ManagerBehaviour`.
Create an CameraManager class which extends from `ManagerBehaviour`.

Create an empty GameObject and add the AudioManager component.
Create an empty GameObject and add the CameraManager component.

Run the game and you will see that the second game object with the CameraManager attached is removed from the scene.

**Comment by SamuelKnox** [comment]
Nice catch.  It happens when there are multiple duplicate ManagerBehaviours that need to be destroyed.  I fixed that issue, (but created a new low priority bug).  I actually moved the repo to https://github.com/Evorlor/Custom-Unity-Library and did some major cleanup.  You can get the updated version there, and I will fix the bug as soon as I figure it out.

Thanks for your help!!

**Comment by CaptainRedmuff** [comment]
Did you manage to resolve the low priority bug?

I am able to reproduce the same issue using the updated `ManagerBehaviour` class in the new repo (https://github.com/Evorlor/Custom-Unity-Library)

**Comment by SamuelKnox** [comment]
That's not something I considered. Thanks and nice find! I'll copy your issue here and open it as an issue on the new repo and try to find a fix for it. Thanks!

**Comment by CaptainRedmuff** [comment]
Apologies. I should have raised this issue against the new repo. I was curious as to what the low priority bug was that you had identified. I'll raise any further issues against the new repo.
